### Variables
@baseUrl = http://localhost:3000/api/v1
@contentType = application/json
@Cookie= access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyYTY1OWQxLWNjODItNDhkYS1hODcxLWZiMjNkNDVlZmE5YSIsInVzZXJuYW1lIjoiZWMyIiwiZW1haWwiOiJlY2ZyZWVpbnN0YW5jZUBnbWFpbC5jb20iLCJpYXQiOjE3NjgyMzM0NDEsImV4cCI6MTc2ODI0NDI0MX0.QneHpJ6MVC-5T5zHDkl47viXTDsnRWJZEEyodr2NrZk;  
### Register a new user
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
    "username": "ec2",
    "email": "ecfreeinstance@gmail.com",
    "password": "ZD6K6;:Ep2?!F:u"
}

###

### Login User
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "username": "ec2",
    "password": "ZD6K6;:Ep2?!F:u"
}

###
GET {{baseUrl}}/info
Cookie: {{Cookie}}
Content-Type: {{contentType}}


### =========================
### Create Content
### POST /content
### =========================
POST {{baseUrl}}/content
Content-Type: {{contentType}}
Cookie: {{Cookie}}

{
  "title": "My youtbe Blog",
  "content": "This is the content body",
  "link": "https://example.com",
  "tags": ["backend", "node", "prisma"],
  "type": "youtube",
  "isPublic": false
}

###

### =========================
### Get Content (pagination)
### GET /content?skip=0&limit=10
### =========================
GET {{baseUrl}}/content?skip=0&limit=40
Content-Type: {{contentType}}
Cookie: {{Cookie}}

###

### =========================
### Update Content by ID (PATCH-like)
### PUT /content/:contentId
### =========================
PATCH  {{baseUrl}}/content/1e8e2798-e9b7-4be9-919c-f184b4e6c96d
Content-Type: {{contentType}}
Cookie: {{Cookie}}

{
  "title": "updated title",
  "content": "Updated content text",
  "tags": "node,exprss,prisma",
  "isPublic": false
}

###

### =========================
### Delete Content by ID
### DELETE /content/:contentId
### =========================
DELETE {{baseUrl}}/content/fbb5e5b4-724f-4f1e-a7b3-212c7c0bb681
Content-Type: {{contentType}}
Cookie: {{Cookie}}

###

### =========================
### Delete ALL Content for User
### DELETE /content
### =========================
DELETE {{baseUrl}}/content
Content-Type: {{contentType}}
Cookie: {{Cookie}}



### =========================
### Create/Share Link
### POST /share
### =========================
GET  {{baseUrl}}/share?share=true
Content-Type: {{contentType}}
Cookie: {{Cookie}}


## =========================
### Get Content Using Share Link
### GET /share/:hash
### =========================
GET {{baseUrl}}/share/ff3b8e47-218f-4175-af8a-c85da52b903f
Content-Type: {{contentType}}

## =========================
### Get Content by type
### 
### =========================
GET {{baseUrl}}/content-type?type=youtube
Content-Type: {{contentType}}
Cookie: {{Cookie}}

#### View the setting of the user 
GET {{baseUrl}}/setting
Content-Type: {{contentType}}
Cookie: {{Cookie}}



#### Update the setting of the user 
PUT {{baseUrl}}/setting
Content-Type: {{contentType}}
Cookie: {{Cookie}}

{
  "deactivateAccount": false
}

### Logout the user 
GET {{baseUrl}}/logout
Content-Type: {{contentType}}
Cookie: {{Cookie}}


### initate email verification 
GET {{baseUrl}}/initate-verification
Content-Type: {{contentType}}
Cookie: {{Cookie}}



### verified user email address
GET {{baseUrl}}/verification/e75b8d7b-fe1f-40e6-ae58-897c75a04dbf
Content-Type: {{contentType}}
Cookie: {{Cookie}}

