INSERT INTO "Setting" ( 
      "id",
      "userId",
      "deactivateAccount",
      "deleteAccount",
      "deactivateLinks",
      "deleteLinks",
      "language",
      "grantPersonalData",
      "createdAt",
      "updatedAt"
) 
SELECT 
    gen_random_uuid(),
    "id",
    false, 
    false, 
    false,
    false, 
    'en', 
    true, 
    NOW(), 
    NOW()
FROM "User" 
WHERE "id" NOT IN (SELECT "userId" FROM "Setting");

-- 2. The index Prisma generated by prisma
CREATE UNIQUE INDEX "Link_hash_key" ON "Link"("hash");